version: '3.9'
services:
  server:
    build:
      context: .
      target: build
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
