name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
    - env:
        DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
        FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      run: docker-compose up
